package files

// FileDesc describes a file type with its properties.
type FileDesc struct {
	Name         string
	Category     string
	MimeType     string
	IsBinary     bool
	IsCompressed bool
	IsExecutable bool
}

var fileDescriptions = map[string]FileDesc{
	// Document.
	DOC: {
		Name:         "Microsoft Word Document",
		Category:     CategoryDocument,
		MimeType:     "application/msword",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	DOCX: {
		Name:         "Microsoft Word Document (XML)",
		Category:     CategoryDocument,
		MimeType:     "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	DOT: {
		Name:         "Microsoft Word Document Template",
		Category:     CategoryDocument,
		MimeType:     "application/msword",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	DOTX: {
		Name:         "Microsoft Word Document Template (XML)",
		Category:     CategoryDocument,
		MimeType:     "application/vnd.openxmlformats-officedocument.wordprocessingml.template",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	DOTM: {
		Name:         "Microsoft Word Document Template (Macro-enabled)",
		Category:     CategoryDocument,
		MimeType:     "application/vnd.ms-word.template.macroEnabled.main+xml",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	ODT: {
		Name:         "OpenDocument Text Document",
		Category:     CategoryDocument,
		MimeType:     "application/vnd.oasis.opendocument.text",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	OTT: {
		Name:         "OpenDocument Text Template",
		Category:     CategoryDocument,
		MimeType:     "application/vnd.oasis.opendocument.text-template",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	PDF: {
		Name:         "Portable Document Format",
		Category:     CategoryDocument,
		MimeType:     "application/pdf",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TXT: {
		Name:         "Text File",
		Category:     CategoryDocument,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	RTF: {
		Name:         "Rich Text Format",
		Category:     CategoryDocument,
		MimeType:     "application/rtf",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	MD: {
		Name:         "Markdown Document",
		Category:     CategoryDocument,
		MimeType:     "text/markdown",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	OXPS: {
		Name:         "Open XML Paper Specification",
		Category:     CategoryDocument,
		MimeType:     "application/oxps",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	XPS: {
		Name:         "XML Paper Specification",
		Category:     CategoryDocument,
		MimeType:     "application/vnd.ms-xpsdocument",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	WP: {
		Name:         "WordPerfect Document",
		Category:     CategoryDocument,
		MimeType:     "application/wordperfect",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	WPD: {
		Name:         "WordPerfect Document",
		Category:     CategoryDocument,
		MimeType:     "application/wordperfect",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Spreadsheets.
	XLS: {
		Name:         "Microsoft Excel Spreadsheet",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.ms-excel",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	XLSX: {
		Name:         "Microsoft Excel Spreadsheet (XML)",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	XLSM: {
		Name:         "Microsoft Excel Spreadsheet (Macro-enabled)",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.ms-excel.sheet.macroEnabled.main+xml",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	XLT: {
		Name:         "Microsoft Excel Spreadsheet Template",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.ms-excel",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	XLTX: {
		Name:         "Microsoft Excel Spreadsheet Template (XML)",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	ODS: {
		Name:         "OpenDocument Spreadsheet",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.oasis.opendocument.spreadsheet",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	SXC: {
		Name:         "OpenOffice.org Calc Spreadsheet",
		Category:     CategorySpreadsheet,
		MimeType:     "application/vnd.sun.xml.calc",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CSV: {
		Name:         "Comma-Separated Values",
		Category:     CategorySpreadsheet,
		MimeType:     "text/csv",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	TSV: {
		Name:         "Tab-Separated Values",
		Category:     CategorySpreadsheet,
		MimeType:     "text/tab-separated-values",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Presentation.
	PPT: {
		Name:         "Microsoft PowerPoint Presentation",
		Category:     CategoryPresentation,
		MimeType:     MimePowerPoint,
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PPTX: {
		Name:         "Microsoft PowerPoint Presentation (XML)",
		Category:     CategoryPresentation,
		MimeType:     "application/vnd.openxmlformats-officedocument.presentationml.presentation",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PPTM: {
		Name:         "Microsoft PowerPoint Presentation (Macro-enabled)",
		Category:     CategoryPresentation,
		MimeType:     "application/vnd.ms-powerpoint.presentation.macroEnabled.main+xml",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	POT: {
		Name:         "Microsoft PowerPoint Presentation Template",
		Category:     CategoryPresentation,
		MimeType:     MimePowerPoint,
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	POTX: {
		Name:         "Microsoft PowerPoint Presentation Template (XML)",
		Category:     CategoryPresentation,
		MimeType:     "application/vnd.openxmlformats-officedocument.presentationml.template",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PPS: {
		Name:         "Microsoft PowerPoint Slide Show",
		Category:     CategoryPresentation,
		MimeType:     MimePowerPoint,
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PPSX: {
		Name:         "Microsoft PowerPoint Slide Show (XML)",
		Category:     CategoryPresentation,
		MimeType:     "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	ODP: {
		Name:         "OpenDocument Presentation",
		Category:     CategoryPresentation,
		MimeType:     "application/vnd.oasis.opendocument.presentation",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Image.
	JPG: {
		Name:         "JPEG Image",
		Category:     CategoryImage,
		MimeType:     "image/jpeg",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	JPEG: {
		Name:         "JPEG Image",
		Category:     CategoryImage,
		MimeType:     "image/jpeg",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	PNG: {
		Name:         "Portable Network Graphics",
		Category:     CategoryImage,
		MimeType:     "image/png",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	GIF: {
		Name:         "Graphics Interchange Format",
		Category:     CategoryImage,
		MimeType:     "image/gif",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	BMP: {
		Name:         "Bitmap Image",
		Category:     CategoryImage,
		MimeType:     "image/bmp",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	TIFF: {
		Name:         "Tagged Image File Format",
		Category:     CategoryImage,
		MimeType:     "image/tiff",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	TIF: {
		Name:         "Tagged Image File",
		Category:     CategoryImage,
		MimeType:     "image/tiff",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SVG: {
		Name:         "Scalable Vector Graphics",
		Category:     CategoryImage,
		MimeType:     "image/svg+xml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	WEBP: {
		Name:         "WebP Image Format",
		Category:     CategoryImage,
		MimeType:     "image/webp",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	ICO: {
		Name:         "Windows Icon",
		Category:     CategoryImage,
		MimeType:     "image/x-icon",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	HEIC: {
		Name:         "High Efficiency Image Format (HEIF)",
		Category:     CategoryImage,
		MimeType:     "image/heic",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	HEIF: {
		Name:         "High Efficiency Image Format",
		Category:     CategoryImage,
		MimeType:     "image/heif",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	RAW: {
		Name:         "RAW Image Format",
		Category:     CategoryImage,
		MimeType:     "image/x-raw",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	CR2: {
		Name:         "Canon RAW Image (Version 2)",
		Category:     CategoryImage,
		MimeType:     "image/x-canon-cr2",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	NEF: {
		Name:         "Nikon RAW Image",
		Category:     CategoryImage,
		MimeType:     "image/x-nikon-nef",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	ARW: {
		Name:         "Sony RAW Image",
		Category:     CategoryImage,
		MimeType:     "image/x-sony-arw",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PSD: {
		Name:         "Adobe Photoshop Document",
		Category:     CategoryImage,
		MimeType:     "image/vnd.adobe.photoshop",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	AI: {
		Name:         "Adobe Illustrator File",
		Category:     CategoryImage,
		MimeType:     "application/illustrator",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	EPS: {
		Name:         "Encapsulated PostScript",
		Category:     CategoryImage,
		MimeType:     "application/eps",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	INDD: {
		Name:         "Adobe InDesign Document",
		Category:     CategoryImage,
		MimeType:     "application/x-indesign",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SKETCH: {
		Name:         "Sketch Document",
		Category:     CategoryImage,
		MimeType:     "application/x-sketch",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	FIGMA: {
		Name:         "Figma Document",
		Category:     CategoryImage,
		MimeType:     "application/figma",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Audio.
	MP3: {
		Name:         "MP3 Audio File",
		Category:     CategoryAudio,
		MimeType:     "audio/mpeg",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	WAV: {
		Name:         "Waveform Audio File",
		Category:     CategoryAudio,
		MimeType:     "audio/wav",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	FLAC: {
		Name:         "Free Lossless Audio Codec",
		Category:     CategoryAudio,
		MimeType:     "audio/flac",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	AAC: {
		Name:         "Advanced Audio Codec",
		Category:     CategoryAudio,
		MimeType:     "audio/aac",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	OGG: {
		Name:         "Ogg Vorbis Audio File",
		Category:     CategoryAudio,
		MimeType:     "audio/ogg",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	WMA: {
		Name:         "Windows Media Audio",
		Category:     CategoryAudio,
		MimeType:     "audio/x-ms-wma",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	M4A: {
		Name:         "MPEG-4 Audio",
		Category:     CategoryAudio,
		MimeType:     "audio/mp4",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	AIFF: {
		Name:         "Audio Interchange File Format",
		Category:     CategoryAudio,
		MimeType:     "audio/aiff",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	ALAC: {
		Name:         "Apple Lossless Audio Codec",
		Category:     CategoryAudio,
		MimeType:     "audio/x-m4a",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	OPUS: {
		Name:         "Opus Audio Codec",
		Category:     CategoryAudio,
		MimeType:     "audio/opus",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	MID: {
		Name:         "MIDI Sequence",
		Category:     CategoryAudio,
		MimeType:     "audio/midi",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	MIDI: {
		Name:         "MIDI Sequence",
		Category:     CategoryAudio,
		MimeType:     "audio/midi",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Video.
	MP4: {
		Name:         "MPEG-4 Video File",
		Category:     CategoryVideo,
		MimeType:     "video/mp4",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	AVI: {
		Name:         "Audio Video Interleave",
		Category:     CategoryVideo,
		MimeType:     "video/x-msvideo",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	MKV: {
		Name:         "Matroska Video File",
		Category:     CategoryVideo,
		MimeType:     "video/x-matroska",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	MOV: {
		Name:         "QuickTime Movie File",
		Category:     CategoryVideo,
		MimeType:     "video/quicktime",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	WMV: {
		Name:         "Windows Media Video",
		Category:     CategoryVideo,
		MimeType:     "video/x-ms-wmv",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	FLV: {
		Name:         "Flash Video File",
		Category:     CategoryVideo,
		MimeType:     "video/x-flv",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	WEBM: {
		Name:         "WebM Video File",
		Category:     CategoryVideo,
		MimeType:     "video/webm",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	M4V: {
		Name:         "MPEG-4 Video (iTunes)",
		Category:     CategoryVideo,
		MimeType:     "video/x-m4v",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	MPEG: {
		Name:         "MPEG Video",
		Category:     CategoryVideo,
		MimeType:     "video/mpeg",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	MPG: {
		Name:         "MPEG Video",
		Category:     CategoryVideo,
		MimeType:     "video/mpeg",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	THREEGP: {
		Name:         "3GPP Multimedia File",
		Category:     CategoryVideo,
		MimeType:     "video/3gpp",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	THREEG2: {
		Name:         "3GPP2 Multimedia File",
		Category:     CategoryVideo,
		MimeType:     "video/3gpp2",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	M2TS: {
		Name:         "MPEG-2 Transport Stream",
		Category:     CategoryVideo,
		MimeType:     "video/mp2t",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	MTS: {
		Name:         "AVCHD Video",
		Category:     CategoryVideo,
		MimeType:     "video/mp2t",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	VOB: {
		Name:         "DVD Video Object",
		Category:     CategoryVideo,
		MimeType:     "video/dvd",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TS_VIDEO: {
		Name:         "MPEG Transport Stream",
		Category:     CategoryVideo,
		MimeType:     "video/MP2T",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},

	// Archive/Compressed.
	ZIP: {
		Name:         "ZIP Archive",
		Category:     CategoryArchive,
		MimeType:     "application/zip",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	RAR: {
		Name:         "RAR Archive",
		Category:     CategoryArchive,
		MimeType:     "application/vnd.rar",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TAR: {
		Name:         "TAR Archive",
		Category:     CategoryArchive,
		MimeType:     "application/x-tar",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	GZ: {
		Name:         "Gzip Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     MimeGzip,
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	GZIP: {
		Name:         "Gzip Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     MimeGzip,
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	SEVENZ: {
		Name:         "7-Zip Archive",
		Category:     CategoryArchive,
		MimeType:     "application/x-7z-compressed",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	BZ2: {
		Name:         "Bzip2 Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     "application/x-bzip2",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	XZ: {
		Name:         "XZ Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     "application/x-xz",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TGZ: {
		Name:         "Gzip Compressed Tarball",
		Category:     CategoryArchive,
		MimeType:     MimeGzip,
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TAR_GZ: {
		Name:         "Gzip Compressed Tarball",
		Category:     CategoryArchive,
		MimeType:     MimeGzip,
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TAR_BZ2: {
		Name:         "Bzip2 Compressed Tarball",
		Category:     CategoryArchive,
		MimeType:     "application/x-bzip2",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	TAR_XZ: {
		Name:         "XZ Compressed Tarball",
		Category:     CategoryArchive,
		MimeType:     "application/x-xz",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	ZST: {
		Name:         "Zstandard Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     "application/zstd",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	LZ4: {
		Name:         "LZ4 Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     "application/lz4",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	LZH: {
		Name:         "LZH Compressed Archive",
		Category:     CategoryArchive,
		MimeType:     "application/x-lzh-compressed",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	CAB: {
		Name:         "Windows Cabinet Archive",
		Category:     CategoryArchive,
		MimeType:     "application/vnd.ms-cab-compressed",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	ISO: {
		Name:         "ISO Disc Image",
		Category:     CategoryArchive,
		MimeType:     "application/x-iso9660-image",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Executable/System.
	EXE: {
		Name:         "Windows Executable File",
		Category:     CategoryExecutable,
		MimeType:     "application/x-msdownload",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: true,
	},
	MSI: {
		Name:         "Windows Installer Package",
		Category:     CategoryExecutable,
		MimeType:     "application/x-msi",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: true,
	},
	SHELLSCRIPT: {
		Name:         "Shell Script (Unix/Linux)",
		Category:     CategoryExecutable,
		MimeType:     "application/x-sh",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	BASH: {
		Name:         "Bash Shell Script",
		Category:     CategoryExecutable,
		MimeType:     "application/x-sh",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	ZSH: {
		Name:         "Z Shell Script",
		Category:     CategoryExecutable,
		MimeType:     "application/x-zsh",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	FISH: {
		Name:         "Fish Shell Script",
		Category:     CategoryExecutable,
		MimeType:     "application/x-fish",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	BAT: {
		Name:         "Batch File (Windows)",
		Category:     CategoryExecutable,
		MimeType:     "application/x-bat",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	CMD: {
		Name:         "Command Script (Windows)",
		Category:     CategoryExecutable,
		MimeType:     "application/x-cmd",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	PS1: {
		Name:         "PowerShell Script",
		Category:     CategoryExecutable,
		MimeType:     "application/x-powershell",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	APP: {
		Name:         "macOS Application Bundle",
		Category:     CategoryExecutable,
		MimeType:     "application/x-mach-binary",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: true,
	},
	DMG: {
		Name:         "macOS Disk Image",
		Category:     CategoryExecutable,
		MimeType:     "application/x-apple-diskimage",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	DEB: {
		Name:         "Debian Package",
		Category:     CategoryExecutable,
		MimeType:     "application/vnd.debian.binary-package",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: true,
	},
	RPM: {
		Name:         "RPM Package",
		Category:     CategoryExecutable,
		MimeType:     "application/x-rpm",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: true,
	},
	APPIMAGE: {
		Name:         "AppImage Package",
		Category:     CategoryExecutable,
		MimeType:     "application/vnd.appimage",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: true,
	},

	// Code - Web.
	HTML: {
		Name:         "HTML Document",
		Category:     CategoryCode,
		MimeType:     "text/html",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	HTM: {
		Name:         "HTML Document",
		Category:     CategoryCode,
		MimeType:     "text/html",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CSS: {
		Name:         "Cascading Style Sheets",
		Category:     CategoryCode,
		MimeType:     "text/css",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	SCSS: {
		Name:         "Sass (SCSS)",
		Category:     CategoryCode,
		MimeType:     "text/x-scss",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	SASS: {
		Name:         "Sass (Indented)",
		Category:     CategoryCode,
		MimeType:     "text/x-sass",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	LESS: {
		Name:         "Less CSS",
		Category:     CategoryCode,
		MimeType:     "text/x-less",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	JS: {
		Name:         "JavaScript File",
		Category:     CategoryCode,
		MimeType:     "text/javascript",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	JSX: {
		Name:         "React JavaScript XML",
		Category:     CategoryCode,
		MimeType:     "text/jsx",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	TS: {
		Name:         "TypeScript File",
		Category:     CategoryCode,
		MimeType:     "text/typescript",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	TSX: {
		Name:         "React TypeScript XML",
		Category:     CategoryCode,
		MimeType:     "text/tsx",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	VUE: {
		Name:         "Vue.js Component",
		Category:     CategoryCode,
		MimeType:     "text/x-vue",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	SVELTE: {
		Name:         "Svelte Component",
		Category:     CategoryCode,
		MimeType:     "text/x-svelte",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	SLIM: {
		Name:         "Slim Template",
		Category:     CategoryCode,
		MimeType:     "text/x-slim",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	ERB: {
		Name:         "Embedded Ruby",
		Category:     CategoryCode,
		MimeType:     "text/x-eruby",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Code - Languages.
	PY: {
		Name:         "Python Script",
		Category:     CategoryCode,
		MimeType:     MimePython,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	PYW: {
		Name:         "Python GUI Script",
		Category:     CategoryCode,
		MimeType:     MimePython,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	GO: {
		Name:         "Go Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-go",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CPP: {
		Name:         "C++ Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-c++src",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CC: {
		Name:         "C++ Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-c++src",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	C: {
		Name:         "C Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-csrc",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	H: {
		Name:         "C/C++ Header",
		Category:     CategoryCode,
		MimeType:     "text/x-chdr",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	HH: {
		Name:         "C++ Header",
		Category:     CategoryCode,
		MimeType:     "text/x-c++hdr",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	HPP: {
		Name:         "C++ Header",
		Category:     CategoryCode,
		MimeType:     "text/x-c++hdr",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	JAVA: {
		Name:         "Java Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-java",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CLASS: {
		Name:         "Java Class File",
		Category:     CategoryCode,
		MimeType:     "application/java-vm",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: true,
	},
	KT: {
		Name:         "Kotlin Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-kotlin",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	KTS: {
		Name:         "Kotlin Script",
		Category:     CategoryCode,
		MimeType:     "text/x-kotlin",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	SCALA: {
		Name:         "Scala Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-scala",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	SWIFT: {
		Name:         "Swift Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-swift",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	RB: {
		Name:         "Ruby Script",
		Category:     CategoryCode,
		MimeType:     "text/x-ruby",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	RUBY: {
		Name:         "Ruby Script",
		Category:     CategoryCode,
		MimeType:     "text/x-ruby",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	PHP: {
		Name:         "PHP Script",
		Category:     CategoryCode,
		MimeType:     "text/x-php",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	RUST: {
		Name:         "Rust Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-rust",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	DART: {
		Name:         "Dart Source Code",
		Category:     CategoryCode,
		MimeType:     "text/x-dart",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	LUA: {
		Name:         "Lua Script",
		Category:     CategoryCode,
		MimeType:     "text/x-lua",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	PERL: {
		Name:         "Perl Script",
		Category:     CategoryCode,
		MimeType:     "text/x-perl",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	PM: {
		Name:         "Perl Module",
		Category:     CategoryCode,
		MimeType:     "text/x-perl",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	RMARKDOWN: {
		Name:         "R Markdown",
		Category:     CategoryCode,
		MimeType:     "text/x-markdown",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Code - Config/Build.
	JSON: {
		Name:         "JavaScript Object Notation",
		Category:     CategoryConfig,
		MimeType:     MimeJSON,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	JSON5: {
		Name:         "JSON5 File",
		Category:     CategoryConfig,
		MimeType:     MimeJSON,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	JSONC: {
		Name:         "JSON with Comments",
		Category:     CategoryConfig,
		MimeType:     MimeJSON,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	XML: {
		Name:         "Extensible Markup Language",
		Category:     CategoryConfig,
		MimeType:     "application/xml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	YAML: {
		Name:         "YAML File",
		Category:     CategoryConfig,
		MimeType:     "text/yaml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	YML: {
		Name:         "YAML File",
		Category:     CategoryConfig,
		MimeType:     "text/yaml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	TOML: {
		Name:         "TOML File",
		Category:     CategoryConfig,
		MimeType:     "application/toml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	INI: {
		Name:         "INI Configuration File",
		Category:     CategoryConfig,
		MimeType:     "text/ini",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CONF: {
		Name:         "Configuration File",
		Category:     CategoryConfig,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CONFIG: {
		Name:         "Configuration File",
		Category:     CategoryConfig,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	ENV: {
		Name:         "Environment File",
		Category:     CategoryConfig,
		MimeType:     "text/x-env",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	PROPERTIES: {
		Name:         "Java Properties File",
		Category:     CategoryConfig,
		MimeType:     "text/x-properties",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	PROPS: {
		Name:         "Properties File",
		Category:     CategoryConfig,
		MimeType:     "text/x-properties",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	GRADLE: {
		Name:         "Gradle Build File",
		Category:     CategoryConfig,
		MimeType:     "text/x-gradle",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	GRADLE_KTS: {
		Name:         "Gradle Kotlin Script",
		Category:     CategoryConfig,
		MimeType:     "text/x-gradle",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	MAKEFILE: {
		Name:         "Makefile",
		Category:     CategoryConfig,
		MimeType:     "text/x-makefile",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	CMAKE: {
		Name:         "CMake Build File",
		Category:     CategoryConfig,
		MimeType:     "text/x-cmake",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	LOCK: {
		Name:         "Lock File",
		Category:     CategoryConfig,
		MimeType:     MimeJSON,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	PACKAGE: {
		Name:         "Package File",
		Category:     CategoryConfig,
		MimeType:     MimeJSON,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	HTACCESS: {
		Name:         "Apache htaccess",
		Category:     CategoryConfig,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Code - Data format.
	SQL: {
		Name:         "SQL Database Query",
		Category:     CategoryData,
		MimeType:     "application/sql",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	GRAPHQL: {
		Name:         "GraphQL Query",
		Category:     CategoryData,
		MimeType:     "application/graphql",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	GQL: {
		Name:         "GraphQL Query",
		Category:     CategoryData,
		MimeType:     "application/graphql",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	MDX: {
		Name:         "MDX Document",
		Category:     CategoryData,
		MimeType:     "text/mdx",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Database.
	DB: {
		Name:         "Database File",
		Category:     CategoryDatabase,
		MimeType:     "application/x-database",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SQLITE: {
		Name:         "SQLite Database",
		Category:     CategoryDatabase,
		MimeType:     "application/vnd.sqlite3",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SQLITE3: {
		Name:         "SQLite Database",
		Category:     CategoryDatabase,
		MimeType:     "application/vnd.sqlite3",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	DB3: {
		Name:         "dBase Database",
		Category:     CategoryDatabase,
		MimeType:     "application/x-dbase",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Certificate/Security.
	PEM: {
		Name:         "PEM Certificate",
		Category:     CategorySecurity,
		MimeType:     "application/x-pem-file",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CRT: {
		Name:         "Certificate File",
		Category:     CategorySecurity,
		MimeType:     MimeX509Cert,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CER: {
		Name:         "Certificate File",
		Category:     CategorySecurity,
		MimeType:     MimeX509Cert,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	DER: {
		Name:         "DER Encoded Certificate",
		Category:     CategorySecurity,
		MimeType:     MimeX509Cert,
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	KEY: {
		Name:         "Private Key File",
		Category:     CategorySecurity,
		MimeType:     "application/x-pem-key",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CSR: {
		Name:         "Certificate Signing Request",
		Category:     CategorySecurity,
		MimeType:     "application/x-pkcs10",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	P12: {
		Name:         "PKCS#12 Certificate Bundle",
		Category:     CategorySecurity,
		MimeType:     "application/x-pkcs12",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PFX: {
		Name:         "PFX Certificate Bundle",
		Category:     CategorySecurity,
		MimeType:     "application/x-pkcs12",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	P7B: {
		Name:         "PKCS#7 Certificate",
		Category:     CategorySecurity,
		MimeType:     "application/x-pkcs7-certificates",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	P7C: {
		Name:         "PKCS#7 Certificate",
		Category:     CategorySecurity,
		MimeType:     "application/x-pkcs7-certificates",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	JKS: {
		Name:         "Java KeyStore",
		Category:     CategorySecurity,
		MimeType:     "application/x-java-keystore",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	GPG: {
		Name:         "GNU Privacy Guard Key",
		Category:     CategorySecurity,
		MimeType:     "application/gpg-key",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PGP: {
		Name:         "Pretty Good Privacy Key",
		Category:     CategorySecurity,
		MimeType:     "application/pgp-keys",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SRL: {
		Name:         "Certificate Serial Number",
		Category:     CategorySecurity,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CRL: {
		Name:         "Certificate Revocation List",
		Category:     CategorySecurity,
		MimeType:     "application/pkix-crl",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Font.
	TTF: {
		Name:         "TrueType Font",
		Category:     CategoryFont,
		MimeType:     "font/ttf",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	OTF: {
		Name:         "OpenType Font",
		Category:     CategoryFont,
		MimeType:     "font/otf",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	WOFF: {
		Name:         "Web Open Font Format",
		Category:     CategoryFont,
		MimeType:     "font/woff",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	WOFF2: {
		Name:         "Web Open Font Format 2",
		Category:     CategoryFont,
		MimeType:     "font/woff2",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	EOT: {
		Name:         "Embedded OpenType Font",
		Category:     CategoryFont,
		MimeType:     "application/vnd.ms-fontobject",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},

	// 3D/CAD.
	OBJ: {
		Name:         "Wavefront 3D Object",
		Category:     Category3D,
		MimeType:     "model/obj",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	FBX: {
		Name:         "Filmbox 3D Model",
		Category:     Category3D,
		MimeType:     MimeOctetStream,
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	STL: {
		Name:         "Stereolithography 3D Model",
		Category:     Category3D,
		MimeType:     "model/stl",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	DWG: {
		Name:         "AutoCAD Drawing",
		Category:     Category3D,
		MimeType:     "image/vnd.dwg",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	DXF: {
		Name:         "Drawing Exchange Format",
		Category:     Category3D,
		MimeType:     "image/vnd.dxf",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	BLEND: {
		Name:         "Blender 3D Project",
		Category:     Category3D,
		MimeType:     "application/x-blender",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	MAX3D: {
		Name:         "3ds Max Scene",
		Category:     Category3D,
		MimeType:     "application/x-3ds-max",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	THREEDS: {
		Name:         "3D Studio Scene",
		Category:     Category3D,
		MimeType:     "application/x-3ds",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	IGES: {
		Name:         "IGES 3D Model",
		Category:     Category3D,
		MimeType:     "model/iges",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	IGS: {
		Name:         "IGES 3D Model",
		Category:     Category3D,
		MimeType:     "model/iges",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	STEP: {
		Name:         "STEP 3D Model",
		Category:     Category3D,
		MimeType:     "model/step",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	STP: {
		Name:         "STEP 3D Model",
		Category:     Category3D,
		MimeType:     "model/step",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	IPT: {
		Name:         "Inventor Part",
		Category:     Category3D,
		MimeType:     "application/x-inventor",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	IAM: {
		Name:         "Inventor Assembly",
		Category:     Category3D,
		MimeType:     "application/x-inventor",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SLDDRPRT: {
		Name:         "SolidWorks Part",
		Category:     Category3D,
		MimeType:     "application/slddrprt",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	SLDDRASM: {
		Name:         "SolidWorks Assembly",
		Category:     Category3D,
		MimeType:     "application/slddrasm",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// eBook.
	EPUB: {
		Name:         "Electronic Publication",
		Category:     CategoryEbook,
		MimeType:     "application/epub+zip",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	MOBI: {
		Name:         "Mobipocket eBook",
		Category:     CategoryEbook,
		MimeType:     "application/x-mobipocket-ebook",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	AZW: {
		Name:         "Amazon Kindle eBook",
		Category:     CategoryEbook,
		MimeType:     "application/x-mobi8-ebook",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	AZW3: {
		Name:         "Amazon Kindle eBook (v3)",
		Category:     CategoryEbook,
		MimeType:     "application/vnd.amazon.mobi8-ebook",
		IsBinary:     true,
		IsCompressed: true,
		IsExecutable: false,
	},
	LIT: {
		Name:         "Microsoft Reader eBook",
		Category:     CategoryEbook,
		MimeType:     "application/x-ms-reader",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	PRC: {
		Name:         "Palm Resource Database",
		Category:     CategoryEbook,
		MimeType:     "application/x-palm-database",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	FB2: {
		Name:         "FictionBook",
		Category:     CategoryEbook,
		MimeType:     "application/x-fictionbook+xml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// DevOps/Cloud.
	TF: {
		Name:         "Terraform File",
		Category:     CategoryCloud,
		MimeType:     "application/vnd.hcl",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	TERRAFORM: {
		Name:         "Terraform Configuration",
		Category:     CategoryCloud,
		MimeType:     "application/vnd.hcl",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	ANSIBLE: {
		Name:         "Ansible Playbook",
		Category:     CategoryCloud,
		MimeType:     "text/x-yaml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	DOCKERFILE: {
		Name:         "Dockerfile",
		Category:     CategoryCloud,
		MimeType:     "text/x-dockerfile",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	DOCKER: {
		Name:         "Docker Configuration",
		Category:     CategoryCloud,
		MimeType:     "application/yaml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	KUBERNETES: {
		Name:         "Kubernetes Configuration",
		Category:     CategoryCloud,
		MimeType:     "application/yaml",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	BZL: {
		Name:         "Bazel Build File",
		Category:     CategoryCloud,
		MimeType:     "text/x-bazel",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},

	// Script/Automation.
	BAKE: {
		Name:         "Rake Build File",
		Category:     CategoryAutomation,
		MimeType:     "text/x-rake",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	FABRIC: {
		Name:         "Fabric Configuration",
		Category:     CategoryAutomation,
		MimeType:     MimePython,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},
	FASTLANE: {
		Name:         "Fastlane Configuration",
		Category:     CategoryAutomation,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: true,
	},

	// Scientist Data.
	NC: {
		Name:         "NetCDF Data",
		Category:     CategoryScientist,
		MimeType:     "application/x-netcdf",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	NETCDF: {
		Name:         "NetCDF Data",
		Category:     CategoryScientist,
		MimeType:     "application/x-netcdf",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	HDF5: {
		Name:         "HDF5 Data",
		Category:     CategoryScientist,
		MimeType:     "application/x-hdf5",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	HDF: {
		Name:         "HDF Data",
		Category:     CategoryScientist,
		MimeType:     "application/x-hdf",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	FITS: {
		Name:         "FITS Astronomical Data",
		Category:     CategoryScientist,
		MimeType:     "application/fits",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Virtual Machine/Disk Image.
	IMG: {
		Name:         "Disk Image",
		Category:     CategoryDiskImage,
		MimeType:     "application/x-raw-disk-image",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	VDI: {
		Name:         "VirtualBox Disk Image",
		Category:     CategoryDiskImage,
		MimeType:     "application/x-virtualbox-vdi",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	VMDK: {
		Name:         "VMware Virtual Disk",
		Category:     CategoryDiskImage,
		MimeType:     "application/x-vmdk",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	VHD: {
		Name:         "Virtual Hard Disk",
		Category:     CategoryDiskImage,
		MimeType:     "application/x-vhd",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	VHDX: {
		Name:         "Virtual Hard Disk (v2)",
		Category:     CategoryDiskImage,
		MimeType:     "application/x-vhdx",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Log.
	LOG: {
		Name:         "Log File",
		Category:     CategoryLog,
		MimeType:     MimePlain,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	DUMP: {
		Name:         "Core Dump File",
		Category:     CategoryTemp,
		MimeType:     "application/x-core-dump",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
	TMP: {
		Name:         "Temporary File",
		Category:     CategoryTemp,
		MimeType:     MimeOctetStream,
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	TEMP: {
		Name:         "Temporary File",
		Category:     CategoryTemp,
		MimeType:     "application/octet-stream",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	BAK: {
		Name:         "Backup File",
		Category:     CategoryTemp,
		MimeType:     "application/x-backup",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	OLD: {
		Name:         "Old File",
		Category:     CategoryTemp,
		MimeType:     "application/x-archive",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	CACHE: {
		Name:         "Cache File",
		Category:     CategoryTemp,
		MimeType:     "application/x-cache",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},

	// Other.
	TORRENT: {
		Name:         "BitTorrent File",
		Category:     CategoryOther,
		MimeType:     "application/x-bittorrent",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	PART: {
		Name:         "Partial Download",
		Category:     CategoryOther,
		MimeType:     "application/x-partial-download",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	DESKTOP: {
		Name:         "Desktop Entry File",
		Category:     CategoryOther,
		MimeType:     "application/x-desktop",
		IsBinary:     false,
		IsCompressed: false,
		IsExecutable: false,
	},
	LNK: {
		Name:         "Windows Shortcut",
		Category:     CategoryOther,
		MimeType:     "application/x-ms-shortcut",
		IsBinary:     true,
		IsCompressed: false,
		IsExecutable: false,
	},
}

// GetFileDesc returns the file description for a given extension.
func GetFileDesc(ext string) (FileDesc, bool) {
	fd, ok := fileDescriptions[ext]
	return fd, ok
}

// GetFileDescName returns the human-readable name for a given extension.
func GetFileDescName(ext string) string {
	if fd, ok := fileDescriptions[ext]; ok {
		return fd.Name
	}
	return "Unknown"
}

// GetFileDescCat returns the category for a given extension.
func GetFileDescCat(ext string) string {
	if fd, ok := fileDescriptions[ext]; ok {
		return fd.Category
	}
	return "Unknown"
}

// IsFileBinary returns whether a file with the given extension is binary.
func IsFileBinary(ext string) *bool {
	if fd, ok := fileDescriptions[ext]; ok {
		return &fd.IsBinary
	}
	return nil
}

// IsFileCompressed returns whether a file with the given extension is typically compressed.
func IsFileCompressed(ext string) *bool {
	if fd, ok := fileDescriptions[ext]; ok {
		return &fd.IsCompressed
	}
	return nil
}

// IsFileExecutable returns whether a file with the given extension is executable.
func IsFileExecutable(ext string) *bool {
	if fd, ok := fileDescriptions[ext]; ok {
		return &fd.IsExecutable
	}
	return nil
}

// GetMimeType returns the MIME type for a given extension.
func GetMimeType(ext string) string {
	if fd, ok := fileDescriptions[ext]; ok {
		return fd.MimeType
	}
	return ""
}
