package files

const (
	// Document.
	DOC  string = "doc"
	DOCX string = "docx"
	DOT  string = "dot"
	DOTX string = "dotx"
	DOTM string = "dotm"
	ODT  string = "odt"
	OTT  string = "ott"
	PDF  string = "pdf"
	TXT  string = "txt"
	RTF  string = "rtf"
	MD   string = "md"
	OXPS string = "oxps"
	XPS  string = "xps"
	WP   string = "wp"
	WPD  string = "wpd"

	// Spreadsheets.
	XLS  string = "xls"
	XLSX string = "xlsx"
	XLSM string = "xlsm"
	XLT  string = "xlt"
	XLTX string = "xltx"
	ODS  string = "ods"
	SXC  string = "sxc"
	CSV  string = "csv"
	TSV  string = "tsv"

	// Presentation.
	PPT  string = "ppt"
	PPTX string = "pptx"
	PPTM string = "pptm"
	POT  string = "pot"
	POTX string = "potx"
	PPS  string = "pps"
	PPSX string = "ppsx"
	ODP  string = "odp"

	// Image.
	JPG    string = "jpg"
	JPEG   string = "jpeg"
	PNG    string = "png"
	GIF    string = "gif"
	BMP    string = "bmp"
	TIFF   string = "tiff"
	TIFF2  string = "tiff"
	TIF    string = "tif"
	SVG    string = "svg"
	WEBP   string = "webp"
	ICO    string = "ico"
	HEIC   string = "heic"
	HEIF   string = "heif"
	RAW    string = "raw"
	CR2    string = "cr2"
	NEF    string = "nef"
	ARW    string = "arw"
	PSD    string = "psd"
	AI     string = "ai"
	EPS    string = "eps"
	INDD   string = "indd"
	SKETCH string = "sketch"
	FIGMA  string = "fig"

	// Audio.
	MP3  string = "mp3"
	WAV  string = "wav"
	FLAC string = "flac"
	AAC  string = "aac"
	OGG  string = "ogg"
	WMA  string = "wma"
	M4A  string = "m4a"
	AIFF string = "aiff"
	ALAC string = "alac"
	OPUS string = "opus"
	MID  string = "mid"
	MIDI string = "midi"

	// Video.
	MP4      string = "mp4"
	AVI      string = "avi"
	MKV      string = "mkv"
	MOV      string = "mov"
	WMV      string = "wmv"
	FLV      string = "flv"
	WEBM     string = "webm"
	M4V      string = "m4v"
	MPEG     string = "mpeg"
	MPG      string = "mpg"
	THREEGP  string = "3gp"
	THREEG2  string = "3g2"
	M2TS     string = "m2ts"
	MTS      string = "mts"
	VOB      string = "vob"
	TS_VIDEO string = "ts_video"

	// Archive/Compressed.
	ZIP     string = "zip"
	RAR     string = "rar"
	TAR     string = "tar"
	GZ      string = "gz"
	GZIP    string = "gzip"
	SEVENZ  string = "7z"
	BZ2     string = "bz2"
	XZ      string = "xz"
	TGZ     string = "tgz"
	TAR_GZ  string = "tar.gz"
	TAR_BZ2 string = "tar.bz2"
	TAR_XZ  string = "tar.xz"
	ZST     string = "zst"
	LZ4     string = "lz4"
	LZH     string = "lzh"
	CAB     string = "cab"
	ISO     string = "iso"

	// Executable/System.
	EXE         string = "exe"
	MSI         string = "msi"
	SHELLSCRIPT string = "sh"
	BASH        string = "bash"
	ZSH         string = "zsh"
	FISH        string = "fish"
	BAT         string = "bat"
	CMD         string = "cmd"
	PS1         string = "ps1"
	APP         string = "app"
	DMG         string = "dmg"
	DEB         string = "deb"
	RPM         string = "rpm"
	APPIMAGE    string = "appimage"

	// Code - Web.
	HTML   string = "html"
	HTM    string = "htm"
	CSS    string = "css"
	SCSS   string = "scss"
	SASS   string = "sass"
	LESS   string = "less"
	JS     string = "js"
	JSX    string = "jsx"
	TS     string = "ts"
	TSX    string = "tsx"
	VUE    string = "vue"
	SVELTE string = "svelte"
	SLIM   string = "slim"
	ERB    string = "erb"

	// Code - Languages.
	PY        string = "py"
	PYW       string = "pyw"
	GO        string = "go"
	CPP       string = "cpp"
	CC        string = "cc"
	C         string = "c"
	H         string = "h"
	HH        string = "hh"
	HPP       string = "hpp"
	JAVA      string = "java"
	CLASS     string = "class"
	KT        string = "kt"
	KTS       string = "kts"
	SCALA     string = "scala"
	SWIFT     string = "swift"
	RB        string = "rb"
	RUBY      string = "ruby"
	PHP       string = "php"
	RUST      string = "rust"
	DART      string = "dart"
	LUA       string = "lua"
	PERL      string = "pl"
	PM        string = "pm"
	RMARKDOWN string = "rmd"

	// Code - Config/Build.
	JSON       string = "json"
	JSON5      string = "json5"
	JSONC      string = "jsonc"
	XML        string = "xml"
	YAML       string = "yaml"
	YML        string = "yml"
	TOML       string = "toml"
	INI        string = "ini"
	CONF       string = "conf"
	CONFIG     string = CategoryConfig
	ENV        string = "env"
	PROPERTIES string = "properties"
	PROPS      string = "props"
	GRADLE     string = "gradle"
	GRADLE_KTS string = "gradle.kts"
	MAKEFILE   string = "makefile"
	CMAKE      string = "cmake"
	LOCK       string = "lock"
	PACKAGE    string = "package"
	HTACCESS   string = "htaccess"

	// Code - Data format.
	SQL     string = "sql"
	GRAPHQL string = "graphql"
	GQL     string = "gql"
	MDX     string = "mdx"

	// Database.
	DB      string = "db"
	SQLITE  string = "sqlite"
	SQLITE3 string = "sqlite3"
	DB3     string = "db3"

	// Certificate/Security.
	PEM string = "pem"
	CRT string = "crt"
	CER string = "cer"
	DER string = "der"
	KEY string = "key"
	CSR string = "csr"
	P12 string = "p12"
	PFX string = "pfx"
	P7B string = "p7b"
	P7C string = "p7c"
	JKS string = "jks"
	GPG string = "gpg"
	PGP string = "pgp"
	SRL string = "srl"
	CRL string = "crl"

	// Font.
	TTF   string = "ttf"
	OTF   string = "otf"
	WOFF  string = "woff"
	WOFF2 string = "woff2"
	EOT   string = "eot"

	// 3D/CAD.
	OBJ      string = "obj"
	FBX      string = "fbx"
	STL      string = "stl"
	DWG      string = "dwg"
	DXF      string = "dxf"
	BLEND    string = "blend"
	MAX3D    string = "max"
	THREEDS  string = "3ds"
	IGES     string = "iges"
	IGS      string = "igs"
	STEP     string = "step"
	STP      string = "stp"
	IPT      string = "ipt"
	IAM      string = "iam"
	SLDDRPRT string = "sldprt"
	SLDDRASM string = "slddrw"

	// eBook.
	EPUB string = "epub"
	MOBI string = "mobi"
	AZW  string = "azw"
	AZW3 string = "azw3"
	LIT  string = "lit"
	PRC  string = "prc"
	FB2  string = "fb2"

	// DevOps/Cloud.
	TF         string = "tf"
	TERRAFORM  string = "terraform"
	ANSIBLE    string = "ansible"
	DOCKERFILE string = "dockerfile"
	DOCKER     string = "docker"
	KUBERNETES string = "k8s"
	BZL        string = "bzl"

	// Script/Automation.
	BAKE     string = "rake"
	FABRIC   string = "fabric"
	FASTLANE string = "fastlane"

	// Scientist Data.
	NC     string = "nc"
	NETCDF string = "netcdf"
	HDF5   string = "h5"
	HDF    string = "hdf"
	FITS   string = "fits"

	// Virtual Machine/Disk Image.
	IMG  string = "img"
	VDI  string = "vdi"
	VMDK string = "vmdk"
	VHD  string = "vhd"
	VHDX string = "vhdx"

	// Log/temp.
	LOG      string = "log"
	LOGS     string = "logs"
	LOCKFILE string = "lockfile"
	PID      string = "pid"
	DUMP     string = "dump"
	TMP      string = "tmp"
	TEMP     string = "temp"
	BAK      string = "bak"
	OLD      string = "old"
	CACHE    string = "cache"

	// Other.
	TORRENT string = "torrent"
	PART    string = "part"
	DESKTOP string = "desktop"
	LNK     string = "lnk"
)
